### ISSUE TITLE
modules called "source", "build", "test", etc. should cause an error

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/yotta#105]
If someone tries to create a test module called "test", they're going to get confused very quickly with the test directory.

cc @kflautner

**Comment by mfiore02** [comment]
Hi guys,
I just ran into this problem and it took me and @BlackstoneEngineering a couple hours to figure out what was going on! It would be nice if there was at least a warning message that gets displayed when somebody tries to build a module with a reserved name.
-Mike @ MultiTech
