### ISSUE TITLE
`yotta run <programname>` subcommand

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/yotta#109]
Should run the program either natively, or after loading it onto the target. This will need support defined by target descriptions.

~~Related: the `yotta debug` subcommand should accept program names without the full path, and find them for you.~~ (see 4f3fd5c2c92826ecec64741b12e41aafa98d411a)

**Comment by mpg** [comment]
+1 on this. For executable modules, <programname> could be optional, defaulting to the main program.

Icing on the cake would be an option to also start a serial terminal connects to the device, maybe using pySerial (I think mbed 2's make.py had an option for that).

**Comment by autopulated** [comment]
Added by #741 (released in yotta 0.15.0)
