### ISSUE TITLE
add check for updates that are prevented due to versioned module includes

### ISSUE THREAD

**Issue by meriac** [ARMmbed/yotta#117]
For partner releases and development I would like have a possibility to check if a version-dependency-rule prevents me from using a newer version of a given packet.

The background of this feature request is to detect if we missed to update a module version dependency rule.

We can detect for a partner release if we missed to increment a version number to allow inclusion of a update module and prevent to ship a broken dependency by accidentally not referring to the latest version of a packet.

**Comment by autopulated** [comment]
This was implemented by #368

**Comment by meriac** [comment]
Cool, thanks a lot - Tested and verified!
