### ISSUE TITLE
Yotta Build command fails in Windows if the directory path contains a space.

### ISSUE THREAD

**Issue by sscaglia** [ARMmbed/yotta#133]
Yotta Build command fails in Windows if the directory path contains a space.

In the following image, CMake can't find source file (Directory is 
C:\Projects\ARM IoT\Yotta_test\helloyotta-master (with a space in ARM IoT ). Removing the space, it works fine.

![image](https://cloud.githubusercontent.com/assets/7267721/5519888/42e74be8-8946-11e4-8790-5a01ba4244ac.png)

**Comment by gfarrell** [comment]
Also in unix (Mac OSX) with Yotta 0.0.13
