### ISSUE TITLE
Add ability to define target_properties without a cmakelists.txt file

### ISSUE THREAD

**Issue by thegecko** [ARMmbed/yotta#138]
Moving forward, if we want to try to have yotta auto-generate cmake files for us, we'll need somewhere to declare product-specific target properties.

For example, we have already had a few sneak in (MACOSX_BUNDLE_PLIST for example) and I am seeing the need for a few more (namely XCODE_ATTRIBUTE_* props such as XCODE_ATTRIBUTE_PRODUCT_NAME, XCODE_ATRIBUTE_ASSETCATALOG_COMPILER_APPICON_NAME and XCODE_ATRIBUTE_CODE_SIGN_ENTITLEMENTS)

This approach would also be a valid solution for adding the OTHER_LDFLAGS -ObjC setting previously discussed.

This could be implemented in the module.json file in the form:

```json
"properties" {
    "XCODE_ATTRIBUTE_PRODUCT_NAME": "My Awesome App",
    "MACOSX_BUNDLE_PLIST": "source/Info.plist",
    ...
}
```

This could then be parsed and added during cmakefile generation.
Thoughts?

**Comment by autopulated** [comment]
Why not just set those properties in a CMakeLists file though?

The goal is not for no one to ever need to write CMake – for complex, very specific things, it's reasonable to require custom CMake, and at the moment compiling app bundles is probably one of those specific things.
