### ISSUE TITLE
Installing yotta breaks ubuntu's pip

### ISSUE THREAD

**Issue by stephenpaulger** [ARMmbed/yotta#148]
Following the instructions for Linux installation on http://docs.yottabuild.org/#installing results in a broken pip.

Ubuntu 14.10's version of pip is very old and relies on requests < 2.4. While installing yotta requests>=2.5 is installed.

I think using ubuntu pip to install a newer pip from PyPI before installing yotta should prevent this, but have not tested thoroughly.

**Comment by autopulated** [comment]
This should be fixed by the updated installation instructions, which include installing a new pip.

**Comment by BlackstoneEngineering** [comment]
See video here for instructions : https://www.youtube.com/watch?v=7UtCpvnP7EE
