### ISSUE TITLE
when you `yotta link`, build dependencies are not properly invalidated

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/yotta#157]
(the cmake files aren't touched, because yotta detects that the generated files would be identical, and CMake doesn't seem to pick up the fact the directory has moved)

This could be fixed by reading the source of links and using absolute paths to reference dependency CMakeLists (then the absolute path will change when the module is linked).

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-905
