### ISSUE TITLE
Command line options for yotta init, instead of prompting for information

### ISSUE THREAD

**Issue by shield007** [ARMmbed/yotta#192]
Hi,

Could command line options be added it yotta init command so that it won't prompted for values that it needs. Instead it should be possible to specify them on the command line.

Cheers,
JP.

**Comment by autopulated** [comment]
I've thought about this a little:

`yotta init` is for use by humans. If you want to programatically create a yotta module, please just write the `module.json` file. It's [well documented](http://docs.yottabuild.org/reference/module.html), and has a [schema](https://github.com/ARMmbed/yotta/blob/master/yotta/lib/schema/module.json) which you can verify against.
