### ISSUE TITLE
Specify Python Version in Read.me

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/yotta#193]
In in the "Installation" Section of the readme it needs to be specified and linked which version of python is being used.

### Installation
Detailed instructions can be found on the documentation site, in summary, to use yotta you need:
*    yotta itself (yotta is written in python, and installed using pip)

### Installation
Detailed instructions can be found on the documentation site, in summary, to use yotta you need:
*    yotta itself (yotta is written in python2.7, and installed using pip)

**Comment by autopulated** [comment]
yotta should work with any recent enough version of python (2 or 3), but I'll add a recommendation for python 2 as the best tested version.

**Comment by BlackstoneEngineering** [comment]
We should add a warning to windows users to go an read the documentation, 'cause for them the instructions on the read.me file are no where near enough (PyCrypto, ninja, the order of install, everything)
