### ISSUE TITLE
Smarter windows intstall script

### ISSUE THREAD

**Issue by sg-** [ARMmbed/yotta#209]
See comment thread here. https://github.com/ARMmbed/yotta/pull/132#issuecomment-88221954

**Comment by BlackstoneEngineering** [comment]
## Todo: 
* silent install of dependencies
* check for existence of dependencies before downloading
* ...?

**Comment by BlackstoneEngineering** [comment]
@sg- @autopulated  we should probably schedule this for review soon for the public beta?

**Comment by autopulated** [comment]
PRs welcome :)

My view on this is that the current instructions are sufficient, even though there could be fewer steps. I think that clearly explaining to people what the dependencies are and where they are installed is something that most people appreciate even if they have to manually perform a number of steps.

So yea: easier is always good, but what we have is OK.

**Comment by sg-** [comment]
https://github.com/ARMmbed/yotta_windows_installer Thank you @BlackstoneEngineering This is a great 0.01 :)

**Comment by BlackstoneEngineering** [comment]
Correction: heres an update https://github.com/ARMmbed/yotta_windows_installer/releases/tag/v0.1.0

**Comment by autopulated** [comment]
resolved by #431 :tada: :balloon:
