### ISSUE TITLE
'ls' should also show the module location

### ISSUE THREAD

**Issue by bogdanm** [ARMmbed/yotta#238]
Related to #231: it's a good thing that now we know were we're downloading from, but the same information could be useful later, during a 'yotta ls' command.

**Comment by autopulated** [comment]
Once modules are downloaded, the information about where they came from is no longer available. The location on disk *is* displayed by `ls`, although it is omitted if it corresponds to the location in the displayed module tree.

**Comment by bogdanm** [comment]
<hint>.yotta.json</hint> :laughing:

**Comment by markus-becker-tridonic-com** [comment]
Well, the spec information from the targetDependencies and dependencies would already be a good indicator.

**Comment by autopulated** [comment]
Fixed in `yotta ls -a` and `yotta ls -i` by #574
