### ISSUE TITLE
KeyError: 'SUDO_UID' in fsutils_posix.py

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/yotta#240]
In fsutils_posix.py:21
```
 if os.environ['SUDO_UID']:
```

Will raise a key error if SUDO_UID does not exist in environ. Could do:
```
if 'SUDO_UID' in os.environ.keys():
```
instead.

**Comment by autopulated** [comment]
Could you verify that #243 works OK?

**Comment by LiyouZhou** [comment]
Yes it seem to work without SUDO_UID set.

**Comment by autopulated** [comment]
:thumbsup:
