### ISSUE TITLE
yt build should exit non-zero on all errors

### ISSUE THREAD

**Issue by mpg** [ARMmbed/yotta#246]
One case where it doesn't:

```
% yt build; echo $?
info: generate for target: frdm-k64f-gcc 0.0.16 at /Users/manpeg01/src/mbedtls-examples/tls-client/yotta_targets/frdm-k64f-gcc
error: Installed component mbedtls doesn't match specification >=2.0.0-beta8,<2.1.0 (when trying to find dependencies for tls-client-example)
mbedOS.cmake included
[ ... ]
[100%] Built target tls-client-example
0
```

**Comment by autopulated** [comment]
Try #255 – note that version errors in linked modules may still be missed. This is because the install step  before building doesn't recurse into linked modules at all (the build proceeds assuming linked modules are all in order). If that is a problem please open another issue.
