### ISSUE TITLE
installation instructions should say to use gcc from launchpad

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/yotta#247]
From here: https://launchpad.net/gcc-arm-embedded/+download

(On Ubuntu the built-in arm-none-eabi-gcc fails to find the C++ library headers.)

**Comment by bridadan** [comment]
I remember adding this to the docs. Here's the line where that starts: https://github.com/ARMmbed/yotta/blame/master/docs/index.md#L165

Currently it points to a page that gives information on how to install on Ubuntu specifically. Should this be extended to all OSs?

**Comment by autopulated** [comment]
Ah you totally did. Nevermind.
