### ISSUE TITLE
.yotta_ignore does not handle sub-directories.

### ISSUE THREAD

**Issue by SeppoTakalo** [ARMmbed/yotta#258]
yotta --version: 0.4.1

If we specify following in .yotta_ignore
~~~
test/*
~~~

Yotta will still try to compile test/unittest/xxx.cpp,

So we need to list every subdirectory that we want to ignore.

**Comment by hugovincent** [comment]
Does git-style `test/**` work?

**Comment by autopulated** [comment]
@hugovincent unfortunately not, see #81
