### ISSUE TITLE
mbed version defines for writing portable code

### ISSUE THREAD

**Issue by marcuschangarm** [ARMmbed/yotta#273]
Redirected from: https://github.com/ARMmbed/mbed-sdk-private/issues/27

Original post:
It would be useful to have defines for the major mbed releases, for example

```
#if defined(MBED2)
// do classic mbed stuff
#elif defined(MBEDOS)
// do mbed os stuff
#endif
```

**Comment by autopulated** [comment]
Module version definitions have been needed for a while. How would this format work for you:

```
#define YOTTA_<modulename>_VERSION_STRING "1.2.3-whatever+stuffmightbehere"
#define YOTTA_<modulename>_VERSION_MAJOR 1
#define YOTTA_<modulename>_VERSION_MINOR 2
#define YOTTA_<modulename>_VERSION_PATCH 3
```

**Comment by marcuschangarm** [comment]
Looks great! How would you generate the STRING variant?

**Comment by autopulated** [comment]
From the full semantic version (including any pre-release or build metadata)
