### ISSUE TITLE
Indirect dependencies sometimes do not invoke generation of extraIncludes

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/yotta#285]

**Comment by autopulated** [comment]
I haven't been able to reproduce this (tested indirect setting of the extra include paths via dependencies, testDependencies, targetDependencies, and testTargetDependencies) – do you have a testcase (or any hints about the module structure that exhibited this) that you could share?

**Comment by bremoran** [comment]
Err... Sadly, no.  I've lost track of what caused it now.

**Comment by autopulated** [comment]
I'm going to close this for now then. Please re-open with more information if the problem occurs again.
