### ISSUE TITLE
Implement --save flag for yotta uninstall to remove module from module.json

### ISSUE THREAD

**Issue by thegecko** [ARMmbed/yotta#299]
I would expect yotta to uninstall the module and remove it from the module.json file if a --save flag is passed to the command.

It seems --save has not been implemented and probably should.

This would mimic npm functionality (with --save removes both folder and json entry, without just removes the folder)

**Comment by autopulated** [comment]
This was fixed by #334: `yotta uninstall` now removes the module from module.json.
