### ISSUE TITLE
targets guide needs updating for target inheritance

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/yotta#321]
http://docs.yottabuild.org/tutorial/targets.html

**Comment by BlackstoneEngineering** [comment]
Question: is this the section to add things like how to add a new target sub platform? Like adding frdm-k25z-gcc when target-freescale already exists? If so i might have some relevant experience from what i did a couple months ago. (also this should be done by the public release)

**Comment by autopulated** [comment]
The guide to "writing targets" should cover basing things off an existing target, yes.
