### ISSUE TITLE
Yotta publish multiple versions which have not been published yet

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/yotta#323]
I was not certain if this feature is supported or how it works so I gave it a try today. I made locally 2 versions via yt version xxxx. Then I invoked yotta publish to registry, the latest tag was only published. Is this intended behavior?

If we make more versions, I do I need reset to each tag version and do separate publish command?

**Comment by autopulated** [comment]
Yes, `yotta publish` works only with the working directory, so it will only ever publish the current version.

You can go back and publish an earlier version if necessary by checking it out from your version control, and then invoking `yotta publish`.
