### ISSUE TITLE
Login to new registry should add that registry to search function

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/yotta#338]
# Problem
When you register to a private repository you have no means of searching it by default. You must enter a command like the following each time you want to search the new private repository 
```bash
yt --registry=https://privateAddress.com search ...
```
Having to do this each time you want to search is a major inconvenience and breaks user flow for anyone using a private repository.

# Solution
When registering / login to a new private repository it should be added to the search function. Possibly by keeping a dictionary of registries to search, and displaying which registry results come from. For example

```bash
$ yt search some-private-module

yottabuild.org public registry results:
    no results found.
<privateRepoAddress> registry results:
private-module 0.x.x : description of module
```

**Comment by autopulated** [comment]
Fixed by #346
