### ISSUE TITLE
add contributing.md with link to CLA

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/yotta#342]
Github shows a banner asking people who open pull reqs to read this, so might as well use that.

 * [CLA](https://developer.mbed.org/contributor_agreement/)
 * [github docs on contributing.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)

**Comment by hugovincent** [comment]
You mean CONTRIBUTING.md (case matters apparently):
> In the file name field, type CONTRIBUTING or CONTRIBUTING.md (with all caps!)
(https://help.github.com/articles/setting-guidelines-for-repository-contributors/)

**Comment by bogdanm** [comment]
Good idea. I think we should add that to all repos in ARMmbed.

**Comment by bogdanm** [comment]
(all public ones, that is)

**Comment by autopulated** [comment]
:cry: all caps

**Comment by bogdanm** [comment]
:sob: OH WELL, IT'LL HAVE TO DO.

**Comment by hugovincent** [comment]
Call me oldschool, but for files like this I prefer all-caps... helps visually distinguish the boilerplate in all repos (LICENSE, CONTRIBUTING, README) from the content.

**Comment by autopulated** [comment]
Also worth mentioning [clahub](https://www.clahub.com), which adds a commit status for whether people have agreed to the CLA – we use it for https://github.com/coggle/coggle-translations, has worked really well so far.
