### ISSUE TITLE
Update recomended gcc version on installation instructions for Windows users

### ISSUE THREAD

**Issue by mlnx** [ARMmbed/yotta#354]
The yotta documentation about installating gcc should be updated and be consistent across multiple platforms (e.g. Linux section shows gcc 4.9; Windows section shows gcc 4.8 instead). We should keep updated the latest version known to work with all host OS.
http://docs.yottabuild.org/#installing-on-windows

**Comment by autopulated** [comment]
PRs welcome :)

For the installation guide, this is the file to create a request against: https://github.com/ARMmbed/yotta/blob/master/docs/index.md

**Comment by mlnx** [comment]
Created PR
https://github.com/ARMmbed/yotta/pull/357
