### ISSUE TITLE
yt update: (add option to) show newer versions

### ISSUE THREAD

**Issue by mpg** [ARMmbed/yotta#355]
If I have a module that (test)(target)depends on foo ~0.1.3, and foo 0.2.0 is available in the registry, I'd like yt update to (optionally) give me an info message that 0.2.0 is available, but only (say) 0.1.4 will be installed. This would help me notice and keep depending on the latest version of foo when I upgrade my own module.

See also https://github.com/ARMmbed/yotta-registry/issues/7

**Comment by autopulated** [comment]
see also #117

**Comment by autopulated** [comment]
#368 should fix this :)
