### ISSUE TITLE
Changes in header files (only) do not trigger new build

### ISSUE THREAD

**Issue by AlessandroA** [ARMmbed/yotta#356]
If only header files are changed, yotta does not build the executable again. This was observed both on Linux (make) and Windows (ninja). Tried with 2 different targets (`frdm-k64f-gcc` and `frdm-k64f-armcc`)

**Comment by 0xc0170** [comment]
I can confirm, I have been using yt clean && yt build just in case.

**Comment by autopulated** [comment]
a minimal example that reproduces this would be really useful, if you have one?

**Comment by autopulated** [comment]
For reference, a similar issue was previously resolved here: https://github.com/ARMmbed/target-mbed-gcc/pull/1

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-897

**Comment by autopulated** [comment]
I believe this has been fixed in the target descriptions. Please re-open if it is still a problem.
