### ISSUE TITLE
Downloaded dependencies from private repositories point to unexisting repos

### ISSUE THREAD

**Issue by jagomo** [ARMmbed/yotta#365]
I set a bunch of private repositories were I host some modules and a custom target. When I build the main  application module, the dependencies are also downloaded and store in the yotta_modules and yotta_targets folders respectively.

Nevertheless if you check the contents of the .git/config file, only the one in the main executable module is correct and pointing to the proper repo url.

For instance, my hello world executable module points to:
[remote "origin"]
	url = https://git.mygithot.com/user/example-hello-world.git
	fetch = +refs/heads/*:refs/remotes/origin/*

While the custom target points to
[remote "origin"]
	url = c:\\users\\myusername\\appdata\\local\\temp\\tmpqdanbw
	fetch = +refs/heads/*:refs/remotes/origin/*

And the private modules to:
[remote "origin"]
	url = c:\\users\\myusername\\appdata\\local\\temp\\tmpdsjo3g 
	fetch = +refs/heads/*:refs/remotes/origin/*

where tmpdsjo3g varies from module to module

Shouldn't those origins point to the repos from were the module was originally cloned?

**Comment by autopulated** [comment]
Not sure exactly what you mean – please could you clarify:

> I set a bunch of private repositories were I host some modules
have you specified github-type "username/reponame" dependencies in your module.json file to pull these dependencies?

If so, yotta will use the github API to download the corresponding versions of these dependencies into yotta_modules. It will *not* git-clone them, so there will be no references to them in .git/config.

If, on the other hand you have specified an arbitrary `git+ssh://somewhere-private.com/#~1.2.3` URL in a dependency, then yotta uses git to fetch this: it will first do a shallow clone of the repository into a temporary folder, and the copy out the specific version of your dependency (by looking at tags) that matches, for example, the ~1.2.3 specification, into your yotta_modules.

In neither case will yotta clone something into yotta_modules, and you should not be editing or performing git operations inside yotta_modules, as anything you do there may be overwritten.

Please use [`yotta link`](http://docs.yottabuild.org/reference/commands.html#yotta-link) if you want to simultaneously develop a module and something that it depends on. Note that very close coupling of two modules that requires such development is probably an indication that your modules do not have sufficiently clear interfaces.
