### ISSUE TITLE
yt update does not check testTargetDependencies

### ISSUE THREAD

**Issue by mpg** [ARMmbed/yotta#370]
According to its output on my module, yt update only checks new versions for modules in  targetDependencies and their dependencies, but not for modules listed in testTargetDependencies. (I don't have any target-independent testDependencies, so I don't know if they are checked by yt update or not.)

If there is a good reason to exclude test (target) dependencies by default, then a new option, eg yt update --tests, should be added to allow updating them.

**Comment by autopulated** [comment]
Nope, this is a bug!

**Comment by mpg** [comment]
Hey, can you up the priority of this? I just got a situation where I had to `rm -r yotta_modules` before I could build successfully, because otherwise I was stuck with old conflicting versions that `yt update` wouldn't fix. Thanks!

**Comment by autopulated** [comment]
If you're happy to open a PR and verify that this it works, I think this is a one line change. Try adding `test = True,` here: 
https://github.com/ARMmbed/yotta/blob/master/yotta/update.py#L49

**Comment by mpg** [comment]
Thanks! I'll check that soon (no pending update now).
