### ISSUE TITLE
Implement exit codes on stderr rather than interactive prompts

### ISSUE THREAD

**Issue by thegecko** [ARMmbed/yotta#378]
If a tool (such as a UI integration) is using yotta and the command being run requires the user to log in first, the yotta command will stall awaiting the user to log in. This is very difficult to detect and abstract, so could the interactive sessions be suppressed (perhaps with a switch) to output a known error code in these cases?

e.g.

```yotta publish --non-interactive```

or similar

This way, the command can be run and stderr parsed to guide further commands/interaction.

**Comment by autopulated** [comment]
ack, this should be a top-level option like `--plain` (so it'd be `yotta --non-interactive / -n <subcommand> ...`
