### ISSUE TITLE
Documentation on using CMake

### ISSUE THREAD

**Issue by mlnx** [ARMmbed/yotta#402]
Is there any documentation about using CMake to control the build of a module, instead of using yotta's automatic build system? From the docs this seems to be possible, but it isn't clear how.

**Comment by autopulated** [comment]
The beginnings of some documentation on this are now on the new build-system documentation page here: http://yottadocs.mbed.com/reference/buildsystem.html

The CMake section still needs to be expanded to include more information.

**Comment by autopulated** [comment]
Fixed by #454
