### ISSUE TITLE
Mbed V3.0 IDE Additional Features needed

### ISSUE THREAD

**Issue by star297** [ARMmbed/yotta#406]
If this is not already in the pipeline and possible to achieve, could I ask that a couple of features be added to the V3.0 IDE. Would be useful on V2.0 but I assume this will slowly be phased out.

Availability to set the program load execute address.

Currently Mbed standard is set to 0x00000000. To be able to use the Freescale bootloader features (K20,K22F and K64 in particular) this needs to be set to 0x00008000 for some existing bootloaders.

Editing available for the Toolchain system startup files, e.g. .sct, .s, sys.cpp files.

Currently these are either 'greyed' out or not possible to change unless exported, changed then imported back. This will enable users to program variations of the same Target with different flash/RAM and clock speeds without the need to add additional platforms. Clearly downloading the user program will require an external programmer for instance the Segger Flasher that I have used successfully with the Mbed .BIN generated files.

**Comment by autopulated** [comment]
Thanks for the feedback!

yotta already includes a prototype configuration mechanism (you can read about it [here](http://docs.yottabuild.org/reference/config.html)), which can be used for this (although it isn't yet used for these things in mbed OS).

(Note that the current mbed online IDE does not support yotta or mbed OS)

I'm closing this as there's no bug or feature request on yotta itself here, but if you have any feedback on the above configuration system feel free to open a new ticket.
