### ISSUE TITLE
yotta install can't install mbed-cpputest module 

### ISSUE THREAD

**Issue by cyliangtw** [ARMmbed/yotta#413]
I tried mbed example "mbed-example-asynch-spi" to verify installation of dependent module "mbed-cpputest" by yotta but encountered  "does not exist in the modules registry". In this sample, it only depends on "mbed-cpputest" & "mbed" module, how could I complete yotta_modules by 'yotta install' ?
Show the command & replied error as below:
C:\mbedOS-alpha3\examples\mbed-ex
ample-asynch-spi>yotta install mbed-cpputest
info: get versions for mbed-cpputest
error: mbed-cpputest does not exist in the modules registry. Check that the name
 is correct, and that it has been published.

C:\\mbedOS-alpha3\examples\mbed-ex
ample-asynch-spi>yotta install
info: get versions for mbed
info: get versions for mbed-cpputest
error: Failed to satisfy dependencies of C:\Users\cyliang.NUVOTON\Desktop\ARM_IO
T\ARM_mbed\mbedOS-alpha3\examples\mbed-example-asynch-spi:
error: mbed does not exist in the modules registry. Check that the name is corre
ct, and that it has been published.
error: mbed-cpputest does not exist in the modules registry. Check that the name
 is correct, and that it has been published.

**Comment by 0xc0170** [comment]
Are you using alpha3 release? That release used prefetched modules, therefore yotta install fails as those dependencies have been changed since alpha3, in most cases.

Please use https://github.com/ARMmbed/example-asynch-spi

**Comment by cyliangtw** [comment]
Hi Martin,
        Yes, I am using alpha3 release.
After used your proposed example-asynch-spi. I could finish yotta install except getting the below error.
Do you have any idea to avoid this un-match issue ?

========================================================================
C:\ mbedOS-alpha3\examples\example-asynch-spi-master>yotta install mbed-drivers
info: dependency mbed-drivers is already present in module.json
error: mbed-drivers does not meet specification ~0.7.0 required by minar

BR.
cyliang

**Comment by 0xc0170** [comment]
I'll update examples, thanks for reporting. There is a newer version which resolved this dependency error.

**Comment by autopulated** [comment]
Closing this issue as it relates to example applications, not yotta. Please re-open if this is erroneous.
