### ISSUE TITLE
Windows Jenkins jobs fail due to directory path lengths exceeding MAX_PATH=256 chars

### ISSUE THREAD

**Issue by simonqhughes** [ARMmbed/yotta#424]
Hi

We have configured jenkins on windows 7 enterprise to build ARMmbed repositories. Jenkins uses the windows file system to manage the workspace into which the github plugin clones the repository and then invokes a build using yotta build. This results in paths in the generated directory structure that exceed the windows maximum path length of 255 charachters. For example, the mbed-drivers-nightly-build was configured to run on a slave, and the following path of 264 characters was generated:

C:\temp\workspace\mbed-drivers-nightly-build\label\cam_int_win_hw_1\target\stm32f429i-disco-gcc\build\stm32f429i-disco-gcc\ym\mbed-hal-st-stm32cubef4\source\CMakeFiles\mbed-hal-st-stm32cubef4.dir\c_\temp\workspace\mbed-drivers-nightly-build\label\cam_int_win_hw_1

This means that the job will run the first time (when the dir structure is first created) but thereafter, jenkins cannot remove/update/etc the directory structure because of the long path names.This causes the job to fail thereafter irrevocably with administrator intervention.

The nodes in the path under administrator control are:

the name of the job: mbed-drivers-nightly-build
the name of the jenkins cluster node: cam_int_win_hw_1

This part of the path is currently generated by Jenkins configuration:

C:\temp\workspace\mbed-drivers-nightly-build\label\cam_int_win_hw_1

This amounts to 68 chars. We're investigating how short its possible to make this.

Please can agree on something like the following:
- yotta on windows will not generate paths that exceed the default MAX_PATH-JENKINS_WORKSPACE_ROOT_LEN where MAX_PATH=255 and JENKINS_WORKSPACE_ROOT_LEN=55 ?
- or something similar that has the same outcome

Thanks
Simon

**Comment by autopulated** [comment]
(Please also see #400)

Unfortunately there is no easy solution to this: yotta already flattens the build as much as possible (so it *isn't* the case that more dependencies mean deeper hierarchies). The long path that you list is actually generated mostly by CMake.

CMake already has workarounds for long paths, and should use a hash in the path if the length is going to exceed the limit, so I'm surprised that the path you list exceeds 260 characters (actually, just counting myself: does it - it looks like it's exactly 260 characters without the drive prefix?).

In terms of your specific request, unfortunately yotta is not able to shorten the paths more than it already does (other than potentially changing "build/<targetname>" in the build directory to something shorter). You might be able to use a directory junction to run your build in an alias of your longer path which is actually shorter, to work around any jenkins-imposed directory structures.
