### ISSUE TITLE
`yt uninstall` needs sucessful unintall message

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/yotta#429]
## Problem 
when you run `yt uninstall moduleName` there is no indication to the user that the action has completed sucessfully

## Solution
add "moduleName uninstalled successfully" printout message or fail message as appropriate.

**Comment by autopulated** [comment]
This behaviour is the same as, for example, `rm`. In general unix commands exit silently if there was no error.

`yt clean`, `yt logout`, `yt outdated` and probably other commands will also exit silently if successful.
