### ISSUE TITLE
Yotta dumps traceback on invalid target name

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/yotta#448]
Doing the following sequence of commands will cause yotta to dump a traceback.  A friendlier message, such as "invalid target name" would be nicer.
```
yotta target a.b
yotta update
```

**Comment by autopulated** [comment]
Yup, see https://github.com/ARMmbed/yotta/issues/443 and related issues.

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-892
