### ISSUE TITLE
"yt ls > file" prints terminal escape sequences

### ISSUE THREAD

**Issue by mpg** [ARMmbed/yotta#455]
I'm not sure if this is specific to the yt ls command, but yotta should detect if stdout is a tty and skip writing terminal escape sequences if it isn't, as many commands do with --color-auto.

**Comment by autopulated** [comment]
Yes, yotta should detect this and infer `--plain`. It's possible to work around this for now by using `yt --plain <subcommand>` explicitly.

**Comment by mpg** [comment]
Thanks for the workaround, I never noticed the `--plain` option.
