### ISSUE TITLE
Add warning to yotta link command reference

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/yotta#480]
On windows, yotta link creates directory junctions inside yotta_modules.

Some tools (known to include at least git-bash's `rm -rf`) will traverse these when removing files, potentially causing the unexpected removal of files.

The docs should include a warning about this.

**Comment by bogdanm** [comment]
+1000. `rm -rf` deletes things, but `rmdir /s /q` works just fine.

**Comment by autopulated** [comment]
If rmdir works fine, I suspect that this should also be filed as a bug against msys's rm command?

**Comment by bogdanm** [comment]
Good point, yes. Not exactly sure where I got my `rm` from though :) But I think this issue happened to a number of people using different versions of `rm`.
