### ISSUE TITLE
Support post-config scripts in targets and executables

### ISSUE THREAD

**Issue by hugovincent** [ARMmbed/yotta#518]
Use-case: not all configurations are legal, and not all logic for valid configs can be encoded using techniques like the JSON-Schema approach that has been [previously discussed](https://github.com/ARMmbed/yotta/issues/325). Thus, yotta should offer a way for targets and applications to provide custom logic (e.g. a post-config pre-build script). Since targets are in a hierarchy, yotta should run all such scripts in the target+executable hierarchy and ensure all scripts exit without and error exit code.

**Comment by autopulated** [comment]
'post-config' would be 'pre-build', I think
