### ISSUE TITLE
ninja executable is called ninja-build on Fedora Linux v22

### ISSUE THREAD

**Issue by meriac** [ARMmbed/yotta#524]
Hi James,

it would be nice to check for **ninja-build** in case **ninja** can't be found. My workaround so far:
```bash
sudo ln -s ninja-build /usr/bin/ninja
```
@autopulated

**Comment by autopulated** [comment]
is ninja_build / ninja-build a name that some linux distros use?

**Comment by autopulated** [comment]
Ok should have read the title (=yes, fedora v22). Thanks for reporting this.

**Comment by meriac** [comment]
@autopulated In case you want to test your changes, you can find a VMware image of a yotta installation on Fedora 22 at http://get.meriac.com/ARMmbed.zip

**Comment by autopulated** [comment]
@meriac which version of python ships with fedora v22? (There's a helpful `shutil.which` function in python >=3.3, would be nice to use that)

**Comment by meriac** [comment]
Thanks a lot for the patch!
@autopulated FC22 uses python 2.7

**Comment by autopulated** [comment]
no problem, figured it wasn't too hard to detect things even without shutil.which
