### ISSUE TITLE
Publishing Executables to the registry

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/yotta#533]
There should be a warning message when a user tries to publish executables to the yotta registry. Something like
```shell
$ yt publish
Publishing v0.0.1 of My Module...
WARNING: This module is an executables, it is generally a bad idea to publish executables to the
 registry as they are not re-usable. Are you sure you with to publish this executable to the 
 registry? (Y/N)
```

**Comment by BlackstoneEngineering** [comment]
Something, anything, to somehow discourage this behaviour. I would prefer outright rejection of executables from the registry, but it is what it is.

**Comment by autopulated** [comment]
Yeah, there should be: applications can't be depended on by other modules, so the utility of publishing them is limited.
