### ISSUE TITLE
Require a way to log in to github

### ISSUE THREAD

**Issue by thegecko** [ARMmbed/yotta#539]
When I use a github dependency in yotta and am behind a proxy, github can reach anonymous download limits and refuse to serve requests:

```
github.GithubException.GithubException: 403 {u'documentation_url': u'https://developer.github.com/v3/#rate-limiting', u'message': u"API rate limit exceeded for 81.134.128.130.
```

Can yotta be made to allow github logins?

**Comment by autopulated** [comment]
Thanks for reporting – when this error gets returned, yotta should prompt you to log in automatically.

**Comment by markus-becker-tridonic-com** [comment]
We are hit by this as well. Is there a possibility of a workaround with GitHub's personal access tokens?

**Comment by autopulated** [comment]
If you are accessing private repos the issue won't affect you – so the best workaround is to publish to the registry the things that you are pulling from public githubs.

I'm currently investigating the proper fix for this though, stay tuned!
