### ISSUE TITLE
yotta ls should show whether module is from registry or somewhere else.

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/yotta#569]
It would be great if ```yotta ls``` would show, whether a module is from the registry or not. And if it is not from the registry, the dependency specifier of the location from the module.json should be shown (in red?).

**Comment by autopulated** [comment]
Yes this would definitely be useful, see also #238.

**Comment by autopulated** [comment]
Fixed in `yotta ls -a` and `yotta ls -i` by #574
