### ISSUE TITLE
Add command line option to specify extra config

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/yotta#580]
To support code coverage, I need to be able to specify

```JSON
    "debug" : {
      "options" : {
        "coverage" : true
      }
    }
```

This may only be desirable for some builds, so always-on configuration in application config seems wrong.  Always-on configuration in target config seems wrong.

Therefore, it must be possible to specify code coverage debug builds. One way to do this is to specify either a config file, or a config parameter on the command line.

**Comment by bremoran** [comment]
This is required to support https://github.com/ARMmbed/mbed-drivers/pull/119

**Comment by autopulated** [comment]
Presumably the existing application config.json file doesn't work because you want to do this for a module and its tests?

**Comment by bremoran** [comment]
That is correct
