### ISSUE TITLE
yt unlink does not unlink from local global namespace

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/yotta#584]
## Problem
`c:\ytlib yt link` will link the library module to the local machines global namespace
`c:\ytlib yt unlink` does *not* unlink the library module from the local global namespace, i believe it should. 

Currently there is no mechanism to remove a global namespace symlink.

**Comment by autopulated** [comment]
:thumbsup: Thanks for reporting.

**Comment by autopulated** [comment]
Actually, this was fixed by #586
