### ISSUE TITLE
yotta finishes build, but has non-zero exit code

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/yotta#601]
When yotta finishes building successfully, but has non-critical version incompatibility errors in the install phase, it exits with a non-zero error code. This let's CI tools assume the build failed completely. Is this intended behaviour?

**Comment by autopulated** [comment]
Yes, that's intended: yotta continues to try to build in the face of version errors because often they are non-fatal, but they are still considered errors. Hope that explains things!

**Comment by markus-becker-tridonic-com** [comment]
Would be nice to have a --version-errors-not-fatal option.

**Comment by mlnx** [comment]
@autopulated Is this something that could be considered for one of the short-term releases?

**Comment by autopulated** [comment]
Version errors mean there was a failure, even if the build still succeeded, so I don't see this as high priority: is there a reason it should be?

**Comment by markus-becker-tridonic-com** [comment]
There were quite a few version mismatches lately (mbed-drivers et.al.), which were not fatal, but made the CI system bail out on 'yotta install', so that a build was not even started.

**Comment by markus-becker-tridonic-com** [comment]
Closing my yotta issues.
