### ISSUE TITLE
Add command line macro that identifies the current module

### ISSUE THREAD

**Issue by bogdanm** [ARMmbed/yotta#626]
I'm working on some allocator instrumentation tools (hooking malloc() and related functions) and it'd be quite useful to know the module name from which these functions were called. The simplest way to accomplish this is probably to add the module name as a macro to the compiler command line (`-DYOTTA_CURRENT_MODULE="some-module"`). I tried to add this to `base_CMakeLists.txt`:

```
add_definitions(-DYOTTA_CURRENT_MODULE_NAME=\"{{ component.getName() }}\")
```

But of course this adds multiple macros:

```
-DYOTTA_CURRENT_MODULE_NAME=\"mbed-drivers\" -DYOTTA_CURRENT_MODULE_NAME=\"mbed-hal\" -DYOTTA_CURRENT_MODULE_NAME=\"mbed-hal-frdm-k64f\" -DYOTTA_CURRENT_MODULE_NAME=\"mbed-hal-freescale\" -DYOTTA_CURRENT_MODULE_NAME=\"mbed-hal-k64f\" -DYOTTA_CURRENT_MODULE_NAME=\"mbed-hal-ksdk-mcu\"
```

Is there a simple way to do this with yotta?

**Comment by autopulated** [comment]
OK, it's definitely possible, will have to think about how to do it neatly. Possibly with `COMPILE_DEFINITIONS(_<CONFIG>)` directory property/source file properties, or by using [generator expressions](https://cmake.org/cmake/help/v3.0/manual/cmake-generator-expressions.7.html#manual:cmake-generator-expressions(7)) in `COMPILE_DEFINITIONS`.
