### ISSUE TITLE
Docs say to use yotta.app on OSX but flagged as internal-only pre-release

### ISSUE THREAD

**Issue by beriberikix** [ARMmbed/yotta#644]
The [docs](http://yottadocs.mbed.com/#installing-on-osx) currently mentioned yotta.app as the first way to install yotta. However, the release that is linked clearly states, "[This is an internal-only pre-release not intended for public consumption](https://github.com/ARMmbed/yotta_osx_installer/releases/tag/v0.0.4)."

I suggest adding a note in the docs about the state of yotta.app or removing mention of it untill it becomes stable for public consumption.

**Comment by BlackstoneEngineering** [comment]
It is good to go for public consumption, i'll fix that now.

**Comment by autopulated** [comment]
Thanks for reporting, and thanks @BlackstoneEngineering for fixing!
