### ISSUE TITLE
yotta linked module doesn't get included in the build process

### ISSUE THREAD

**Issue by jrobeson** [ARMmbed/yotta#652]
I created a local module called lbcommon and ran `yotta link`. 
I then went to the module in which I want to use the linked module in and ran `yt link lbcommon`.  

I see the symlink in `yotta_modules/`. I then added `#include lbcommon/util.h"` to my `source/main.cpp` 

I then ran `yotta build` and got this error:

`~/projects/test/source/main.cpp:8:29: fatal error: lbcommon/util.h: No such file or directory`

I looked into `build/nr51dk/ym` and do not see my linked module there.  Should I be seeing it there?

NOTE:  I do override `YOTTA_PREFIX` to use `~/.local/share/yotta/` instead of the default in `/usr/local`. That may or may not be related ot the problem

The yotta version is 0.12.1

**Comment by jrobeson** [comment]
i just tested with `YOTTA_PREFIX` unset , and still have the same problem

**Comment by jrobeson** [comment]
ahh.. of course you still have to set the module as your dependency!

**Comment by autopulated** [comment]
:wink:
