### ISSUE TITLE
Out of date linux environment setup documentation.

### ISSUE THREAD

**Issue by mjs-arm** [ARMmbed/yotta#654]
The documentation in docs/index.md describes how to install a toolchain on a linux box from a PPA.  The PPA referenced is out of date.

The material at:

https://launchpad.net/~terry.guo/+archive/ubuntu/gcc-arm-embedded

has been superseded by:

https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa

**Comment by autopulated** [comment]
:+1: Thanks for reporting this!
