### ISSUE TITLE
Installation issues on Ubuntu 14.04

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/yotta#661]
There are some conflicts between yotta's dependencies and the versions required by system tools on Ubuntu 14.04: either we should recommend using a virtualenv to install, or relax the specifications on dependencies if appropriate.

cc @janjongboom

**Comment by ddavidebor** [comment]
absolutely!

Today this same error emerged to me on ubuntu 14.04:

https://bugs.launchpad.net/openstack-ansible/+bug/1535998

It's related to pip 8.0.0 conflicts.

**Comment by autopulated** [comment]
I think the pip 8.0.0 issues are a separate problem, which I believe pip 8.0.1 has now fixed (`pip install -U pip>=8.0.1`). (This issue was reported before pip 8.0.0 was released)

**Comment by autopulated** [comment]
I've tested the updated instructions in https://github.com/ARMmbed/yotta/pull/673, which will be merged shortly, and I can't reproduce any problems now. Please open a new issue with specific errors if problems are encountered again!
