### ISSUE TITLE
OS abstraction module

### ISSUE THREAD

**Issue by bogdanm** [ARMmbed/yotta#68]
With support for Windows being rolled in, there's this kind of code in various parts of yotta:

if os.name == 'nt' <do_something> else <do_something_else>

In many cases, this breaks the logical flow of the code and may lead to code duplication. To fix this, create an OS abstraction module that hides OS-specific operations in a common interface and replace the code above with calls to this module.

**Comment by autopulated** [comment]
I don't think this turned out to be too bad in the end, so I'm closing this. Please re-open if it's still an issue.
