### ISSUE TITLE
How to build with optimization flags turned down for gdb debugging?

### ISSUE THREAD

**Issue by jacobrosenthal** [ARMmbed/yotta#680]
Im probably just missing this, but yotta is presumably optimizing code so my yt debug sessions leave me with a lot of `<optimized out>`

Presumably id set a flag somehow?

**Comment by 0xc0170** [comment]
Are you building with ```yotta build -d``` ? That should be --debug-build

**Comment by autopulated** [comment]
Yup, use `-d/--debug-build` to reduce optimisation. I noticed this flag could be documented better, so I'm leaving this issue open to track that.

**Comment by jacobrosenthal** [comment]
Nope, thats what I was looking for. Yeah not sure I ran across that in any documentation, but always possible I missed it.
