### ISSUE TITLE
Add --version parameter to yotta

### ISSUE THREAD

**Issue by fvincenzo** [ARMmbed/yotta#687]
Yotta should be able to download a specific version of a package.

i.e. yotta install mbed-drivers --version 0.11.6

**Comment by autopulated** [comment]
:thumbs:

I think the syntax that should be supported is `yotta install <modulename>@<version>`, in fact the docs claim that it should be, so seems like it's a bug :wink: http://yottadocs.mbed.com/reference/commands.html#yotta-install

**Comment by fvincenzo** [comment]
Thanks for the clarification James.

**Comment by autopulated** [comment]
Fixed by #723
