### ISSUE TITLE
Registry: please notice common SCM URLs and make them clickable

### ISSUE THREAD

**Issue by jaustin** [ARMmbed/yotta#692]
When the registry displays the 'Repository' metadata for a module, it shows the data as it was entered in the json

![image](https://cloud.githubusercontent.com/assets/147113/12765340/dd161636-c9c3-11e5-954e-407648d2af46.png)
 http://yotta.mbed.com/#/module/simplelog/1.0.0

It would be great if the registry was clever for common/popular code hosting systems and turned this into a nice link:
![image](https://cloud.githubusercontent.com/assets/147113/12765736/a3c47d9e-c9c5-11e5-9521-1069adae6298.png)

**Comment by autopulated** [comment]
:thumbsup:

**Comment by thegecko** [comment]
Have added this feature for git URLs
