### ISSUE TITLE
Allow modules to specify minimum required yotta version

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/yotta#703]
(cc @jaustin) Possibly something like this:

```JSON
   {
       "yotta": ">=0.1.2"
   }
```

Along the same lines it might be good to have modules specify languages they support too, for example: `"languages": { "C":"99 11", "C++":"98" }`

**Comment by thegecko** [comment]
This is a great idea. Would yotta cease compilation if the version isn't met or just warn?

**Comment by autopulated** [comment]
I think it'd be an "error" that would change the exit status, but otherwise the build would attempt to continue (the same way that version errors are).
