### ISSUE TITLE
yotta fails to build if application name has a space in it.

### ISSUE THREAD

**Issue by pdNor** [ARMmbed/yotta#749]
Application names with space will generate Cmake error se below:

`CMake Error at source/CMakeLists.txt:12 (set_property):
  Syntax error in cmake code at
`
` when parsing string ${YOTTA_AUTO_MBED syntax error, unexpected $end, expecting } (17)`

**Comment by autopulated** [comment]
Module/application names with spaces aren't allowed, so I'm surprised there wasn't an error sooner.

If you have a minimal application that'd reproduce this that'd be really helpful!
