### ISSUE TITLE
HIDError: report size has to be 1025 elements(bytes)

### ISSUE THREAD

**Issue by jsplyy** [ARMmbed/yotta#789]
![yotta](https://cloud.githubusercontent.com/assets/3600912/18006595/e353fe26-6bd2-11e6-871a-d3d5668ce06d.PNG)
I am using frdm-k64 to develop and it has 1M Flash .
Why does it report error?

**Comment by autopulated** [comment]
Looks like a problem in mbedmicro/pyOCD, so might be worth reporting the issue there.
