### ISSUE TITLE
Anonymous read-only access to yotta packages

### ISSUE THREAD

**Issue by finneyj** [ARMmbed/yotta#812]
Hi Folks,

Please see thread here: https://github.com/lancaster-university/microbit-dal/issues/282

Essentially some folks wanting to have ability to use yotta in a read-only fashion without mbed credentials... seems like a reasonable feature request?

**Comment by thegecko** [comment]
@finneyj A very timely request!

We have removed the need to log in to yotta for read-only access today!

Please let us know how you get on.

**Comment by finneyj** [comment]
Serendipitous!

Thanks @thegecko.
