### ISSUE TITLE
Login link results in error after successful login

### ISSUE THREAD

**Issue by carlosperate** [ARMmbed/yotta#819]
Following the link that Yotta prints after `yt login` displays the normal login screen, then after entering the user details correctly, it redirects to:
https://yottabuild.org/#error/Unexpected%20token%20%3C%20in%20JSON%20at%20position%200

And shows as:

![image](https://user-images.githubusercontent.com/4189262/30486457-89a9eb58-9a28-11e7-96a9-1ddf897c1000.png)

The command line then keeps waiting for login until it times out.

Tried in a couple of different PCs running the same vagrant virtualbox set up with Ubuntu 16.04, installing over ssh. Login done in Chrome 60 and Firefox 55 browsers on Windows 10. This is something that was working perfectly fine last week, so wondering if something is broken on the server side.

**Comment by thegecko** [comment]
There hasn't been any changes. Can you try forcing a logout with `yotta logout` first?

**Comment by autopulated** [comment]
It sounds like the API server has returned an html page instead of JSON – heroku temporarily down / reached some rate limit?

**Comment by sgk** [comment]
Exactly same problem here. `yotta logout` does not change the result.

**Comment by thegecko** [comment]
Thanks all for bringing this to our attention. We believe we have found the issue and will deploy a fix as soon as we can.

**Comment by thegecko** [comment]
This issue has been fixed and verified. Apologies for any disruption.

**Comment by carlosperate** [comment]
I can confirm this is working again now, thanks!
