### ISSUE TITLE
error: command ['ninja'] failed

### ISSUE THREAD

**Issue by Rupesh-Gupta** [ARMmbed/yotta#837]
I am trying to build calliope demo program, using my system. I am using Ubuntu 16.04 and have yotta installed. While trying to run the command build all
It gives the following

Build files have been written to: /home/rupesh/Downloads/calliope-demo-master/build/calliope-mini-classic-gcc
[1/1] Linking CXX executable source/calliope-demo
FAILED: : && /usr/bin/arm-none-eabi-g++   -fno-exceptions -fno-unwind-tables -Wl,--gc-sections -Wl,--sort-common -Wl,--sort-section=alignment -Wl,-wrap,main -mcpu=cortex-m0 -mthumb -T"/home/rupesh/Downloads/calliope-demo-master/yotta_targets/calliope-mini-classic-gcc/CMake/../ld/NRF51822.ld" -Wl,-Map,source/calliope-demo.map -Wl,--start-group source/CMakeFiles/calliope-demo.dir/home/rupesh/Downloads/calliope-demo-master/source/Snake.cpp.o source/CMakeFiles/calliope-demo.dir/home/rupesh/Downloads/calliope-demo-master/source/CalliopeDemo.cpp.o source/CMakeFiles/calliope-demo.dir/home/rupesh/Downloads/calliope-demo-master/source/CalliopeTestBoard.cpp.o source/CMakeFiles/calliope-demo.dir/home/rupesh/Downloads/calliope-demo-master/source/CalliopeDemoMaster.cpp.o  ym/microbit/source/microbit.a ym/microbit-dal/source/microbit-dal.a ym/ble/source/ble.a ym/ble-nrf51822/source/ble-nrf51822.a ym/ble/source/ble.a ym/ble-nrf51822/source/ble-nrf51822.a ym/nrf51-sdk/source/nrf51-sdk.a ym/mbed-classic/existing/mbed-classic.a -lnosys  -lstdc++ -lsupc++ -lm -lc -lgcc -lstdc++ -lsupc++ -lm -lc -lgcc -Wl,--end-group  --specs=nano.specs -o source/calliope-demo && cd /home/rupesh/Downloads/calliope-demo-master/build/calliope-mini-classic-gcc/source && arm-none-eabi-objcopy -O ihex calliope-demo calliope-demo.hex && srec_cat /home/rupesh/Downloads/calliope-demo-master/yotta_targets/calliope-mini-classic-gcc/CMake/../bootloader/BLE_BOOTLOADER_RESERVED.hex -intel /home/rupesh/Downloads/calliope-demo-master/yotta_targets/calliope-mini-classic-gcc/CMake/../softdevice/s110_nrf51822_8.0.0_softdevice.hex -intel calliope-demo.hex -intel -o calliope-demo-combined.hex -intel --line-length=44 && cd /home/rupesh/Downloads/calliope-demo-master/build/calliope-mini-classic-gcc/source && /usr/bin/arm-none-eabi-objcopy -O binary calliope-demo calliope-demo.bin

..
/bin/sh: 1: srec_cat: not found
ninja: build stopped: subcommand failed.
error: command ['ninja'] failed

Can someone suggest a solution? I am relatively new to programming using yotta.

**Comment by 0xc0170** [comment]
`srec_cat` this program is missing in your path. It can not be found. Do you have `srec_cat` installed ? See http://srecord.sourceforge.net/man/man1/srec_cat.html
