### ISSUE TITLE
Windows installer link on yotta.docs appears broken

### ISSUE THREAD

**Issue by bobwilmes** [ARMmbed/yotta#853]
The link to the Windows installer for yotta on yottadocs.mbed.com appears broken.
Here is the link:
https://mbed-media.mbed.com/filer_public/2f/0b/2f0b924c-1fac-4907-989b-f2afe3f5785e/yotta_install_v023.exe

**Comment by thegecko** [comment]
Unfortunately the installers are really out of date and we recommend installing yotta using pip.

I've removed the installers from the docs, thanks for your feedback.
